### ISSUE TITLE
Weather entity

### ISSUE THREAD

**Issue by Xan8** [kalanda/homeassistant-aemet-sensor#7]
Is it posible to get an entity_id of the weather (in general, not for specific sensors)?  For example: "weather.aemet". It would be used for [simple-weather-card](https://github.com/kalkih/simple-weather-card) or [weather forecast card](https://www.home-assistant.io/lovelace/weather-forecast/)

**Comment by kalanda** [comment]
I guess is not. I use the sensor `homeassistant.components.sensor` rather than `homeassistant.components.weather` so it requires a fully refactor of the component to adapt it to the weather class.

**Comment by Xan8** [comment]
Thanks.

**Comment by kalanda** [comment]
I decided to add partial support for weather component. 
https://github.com/kalanda/homeassistant-aemet-sensor/releases/tag/v1.1

❗️ Keep in mind that forecast and current condition (sunny, cloudy, ...) aren't available in weather format since AEMET is not providing that information in data format, only as a text description.
