### ISSUE TITLE
Why is not reported as weather service ??

### ISSUE THREAD

**Issue by vincegre** [kalanda/homeassistant-aemet-sensor#8]
Hi

Why is it not considered like a weather service ? it makes it impossible to put it in a weather card in lovelace :(

Thanks

**Comment by kalanda** [comment]
I decided to add partial support for weather component. 
https://github.com/kalanda/homeassistant-aemet-sensor/releases/tag/v1.1

❗️ Keep in mind that forecast and current condition (sunny, cloudy, ...) aren't available in weather format since AEMET is not providing that information in data format, only as a text description.
